# Generated by Django 3.2.6 on 2021-08-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210803_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='describe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, upload_to='game_images'),
        ),
        migrations.AddField(
            model_name='page',
            name='rate',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.page'),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.userprofile')),
            ],
        ),
    ]
